#!/bin/bash

#GUI interface for working ISS via APRS 
#Based on work by Scott Chapman K4KDR
#20200413 KM4ACK


MYPATH=$HOME/Pi-APRS

source $MYPATH/config




##############DEV NOTES##################

#create setup file

##############DEV NOTES##################

mkdir -p $MSGPATH

#Verify not running as root
WHO=$(whoami)
if [ $WHO = 'root' ]; then
echo "no need to run with sudo"
exit
fi

#verify callsign has been set
if [ $MYCALL = "N0CALL" ]; then
yad --width=350 --height=75 --title="N0CALL" --timeout=5 --timeout-indicator=top --no-buttons --center --text="Please choose settings and enter your call sign before using the app"
fi

#Verify needed dependencies are installed

	#check if YAD is installed
	if ! hash yad 2>/dev/null; then
	echo "YAD isn't installed. Please install and try again"
	exit
	fi

	#check if direwolf is installed
	if ! hash direwolf 2>/dev/null; then
	echo "Direwolf isn't installed. Please install and try again"
	exit	
	fi

	#check if ax25 is installed
	AX=$(ls /etc/ax25)
	if [ -z "$AX" ]; then
	echo "AX25 isn't installed. Please install and try again"
	exit
	fi


yad --form --width=250 --image $HOME/Pi-APRS/ISS.png --window-icon=$HOME/Pi-APRS/ISS.png --image-on-top --text="<b>Pi-APRS</b> by KM4ACK" --text-align=center --center --title="Pi-APRS" \
--field="Free Message":fbtn "bash -c 'source $MYPATH/functions; FREEMSG'" \
--field="Status":fbtn "bash -c 'source $MYPATH/functions; SENDSTAT'" \
--field="Heard You":fbtn "bash -c 'source $MYPATH/functions; HEARDU'" \
--field="QSL73":fbtn "bash -c 'source $MYPATH/functions; QSL73'" \
--field="Send Position":fbtn "bash -c 'source $MYPATH/functions; SENDPOS'" \
--field="Start Modems":fbtn "bash -c 'source $MYPATH/functions; STARTMODEM'" \
--field="Settings":fbtn "bash -c 'source $MYPATH/functions; MYCONFIG'" \
--button=gtk-quit:1

QUIT=$?

if [ $QUIT = 1 ] || [ $QUIT = 252 ]; then
DIRE=$(pidof direwolf)
	if [ -z "$DIRE" ]
	then
	echo "Shutting Down"
	sudo killall kissutil > /dev/null 2>&1
	sudo killall direwolf > /dev/null 2>&1
	else
	echo
	echo "######################"
	echo "sending ID before exit"
	echo "######################"
	echo
	source $MYPATH/functions; SENDSTAT
	sleep 2
	sudo killall kissutil > /dev/null 2>&1
	sudo killall direwolf > /dev/null 2>&1
	echo "Shutdown complete"
	fi
fi







